version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      # Android the primary container
      - image: circleci/android:api-27-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      #- restore_cache:
      #    key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: cd AndroidDemo; ./gradlew androidDependencies
      #- save_cache:
      #    paths:
      #      - ~/.gradle
      #    key: jars-{{ checksum "AndroidDemo/build.gradle" }}-{{ checksum  "AndroidDemo/app/build.gradle" }}
      
      - run:
          name: Install Emulator
          command: echo "y" | $ANDROID_HOME/tools/bin/sdkmanager --install 'system-images;android-27;google_apis;armeabi-v7a'
      
      - run:
          name: Setup emulator
          command: avdmanager create avd -n ThanhLeDevice -k "system-images;android-27;default;armeabi-v7a"
      - run:
          name: Launch emulator
          command: nohup $ANDROID_HOME/emulator/emulator -avd ThanhLeDevice -no-snapshot > /dev/null 2>&1 &
          background: true
      - run:
          name: Wait emulator
          command: |
            # wait for it to have booted
            circle-android wait-for-boot
            # unlock the emulator screen
            sleep 10
            adb shell input keyevent 82
            
      - run:
          name: Run EspressoTests
          command: cd AndroidDemo; ./gradlew cAT
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
