version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      # Android the primary container
      - image: circleci/android:api-27-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      #- restore_cache:
      #    key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      #- run:
      #    name: Download Dependencies
      #    command: cd AndroidDemo; ./gradlew androidDependencies
      #- save_cache:
       #   paths:
        #    - ~/.gradle
        #  key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
#       - run:
#           name: List packages
#           command: sdkmanager --list
      
      - run:
          name: Copy SDK License
          command: (echo y; echo y; echo y; echo y; echo y; echo y) | $ANDROID_HOME/tools/bin/sdkmanager --licenses
          
      - run:
          name: Create emulator
          command: |
            set -e
            sdkmanager "system-images;android-22;default;armeabi-v7a"
            echo "no" | avdmanager create avd -n ThanhLeDevice -k "system-images;android-22;default;armeabi-v7a"
            avdmanager list           
      - run:
         name: Launch emulator
         command: emulator -avd ThanhLeDevice -noaudio -no-boot-anim -no-window -accel on
         background: true
      - run:
         name: Wait emulator
         command: circle-android wait-for-boot
      #- run:
      #    name: Run EspressoTests
      #    command: cd AndroidDemo; ./gradlew cAT
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
