version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      # Android the primary container
      - image: circleci/android:api-27
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      #- checkout
      #- restore_cache:
          #key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      #- run:
          #name: Download Dependencies
          #command: cd AndroidDemo; ./gradlew androidDependencies
      #- save_cache:
      #    paths:
      #      - ~/.gradle
      #    key: jars-{{ checksum "AndroidDemo/build.gradle" }}-{{ checksum  "AndroidDemo/app/build.gradle" }}
      - run:
          name: Setup emulator         
          command: |
            apt-get update
            apt-get install wget
            echo y | apt-get install libqt5widgets5

            echo y | sdkmanager "emulator"
            echo y | sdkmanager "platform-tools"
            echo y | sdkmanager "build-tools;26.0.1"
            echo y | sdkmanager "platforms;android-26"
