version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      # Android the primary container
      - image: circleci/android:api-27-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      #- restore_cache:
      #    key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      #- run:
          #name: Download Dependencies
          #command: cd AndroidDemo; ./gradlew androidDependencies
      #- save_cache:
      #    paths:
      #      - ~/.gradle
      #    key: jars-{{ checksum "AndroidDemo/build.gradle" }}-{{ checksum  "AndroidDemo/app/build.gradle" }}
      
      - run:
          name: Install Emulator
          command: echo "y" | $ANDROID_HOME/tools/bin/sdkmanager --install 'system-images;android-25;google_apis;x86_64'
      
      - run:
          name: Setup emulator
          command: echo "no" | $ANDROID_HOME/tools/bin/avdmanager create avd -n ThanhLeDevice -k 'system-images;android-25;google_apis;x86_64' --force; $ANDROID_HOME/emulator/emulator -list-avds
      - run:
          name: Launch emulator
          command: command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd ThanhLeDevice -noaudio -no-boot-anim -no-window -accel auto -verbose
          background: true
      - run:
          name: Wait emulator
          command: |
            # wait for it to have booted
            circle-android wait-for-boot
            # unlock the emulator screen
            #sleep 1
            adb shell input keyevent 82
            $ANDROID_HOME/platform-tools/adb devices
            
      #- run:
          #name: Run EspressoTests
          #command: cd AndroidDemo; ./gradlew cAT
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
