version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      # Android the primary container
      - image: circleci/android:api-27-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      #- restore_cache:
      #    key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      #- run:
      #    name: Download Dependencies
      #    command: cd AndroidDemo; ./gradlew androidDependencies
      #- save_cache:
       #   paths:
        #    - ~/.gradle
        #  key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
#       - run:
#           name: List packages
#           command: sdkmanager --list
      
      - run:
          name: Copy SDK License
          command: printf "8933bad161af4178b1185d1a37fbf41ea5269c55\nd56f5187479451eabf01fb78af6dfcb131a6481e\n24333f8a63b6825ea9c5514f83c2829b004d1fee\n" > ~/android-sdk-linux/licenses/android-sdk-license
          
      - run:
          name: Create emulator
          command: |
            set -e
            sdkmanager "system-images;android-22;default;armeabi-v7a"
            echo "no" | avdmanager create avd -n test -k "system-images;android-22;default;armeabi-v7a"
      #      
      #- run:
      #    name: Launch emulator
      #    command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd test -noaudio -no-boot-anim -no-window -accel on
      #    background: true
      #- run:
      #    name: Wait emulator
      #    command: circle-android wait-for-boot
      #- run:
      #    name: Run EspressoTests
      #    command: cd AndroidDemo; ./gradlew cAT
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
