version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      # Android the primary container
      - image: circleci/android:api-27
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      #- checkout
      #- restore_cache:
      #    key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      #- run:
          #name: Download Dependencies
          #command: cd AndroidDemo; ./gradlew androidDependencies
      #- save_cache:
      #    paths:
      #      - ~/.gradle
      #    key: jars-{{ checksum "AndroidDemo/build.gradle" }}-{{ checksum  "AndroidDemo/app/build.gradle" }}
      
      - run:
          name: Install Emulator
          command: $ANDROID_HOME/tools/bin/sdkmanager --install 'system-images;android-27;google_apis;x86'
      - run:
          name: Setup emulator
          command: $ANDROID_HOME/tools/bin/avdmanager create avd -n ThanhLeDevice -k 'system-images;android-27;google_apis;x86' --force; $ANDROID_HOME/emulator/emulator -list-avds
      
