version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
    - image: circleci/android:api-27-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
    - checkout
    - run:
        name: Download Dependencies
        command: cd AndroidDemo; ./gradlew androidDependencies
    - run:
        name: Copy SDK License
        command: (echo y; echo y; echo y; echo y; echo y; echo y) | $ANDROID_HOME/tools/bin/sdkmanager --licenses
    - run:
        name: Create emulator
        command: |
          sdkmanager "system-images;android-24;default;armeabi-v7a"
          echo "no" | avdmanager create avd -n ThanhLeDevice -k "system-images;android-24;default;armeabi-v7a"
          avdmanager list
    - run:
        name: Launch emulator
        command: emulator -avd ThanhLeDevice -noaudio -no-boot-anim -no-window -accel on
        background: true
    - run:
        name: Wait emulator
        command: circle-android wait-for-boot
    - run:
        name: Check devices
        command: |
          adb devices
          adb shell settings put global development_settings_enabled 1
          adb shell settings put global window_animation_scale 0 &
          adb shell settings put global transition_animation_scale 0 &
          adb shell settings put global animator_duration_scale 0 &
    - run:
        name: Run EspressoTests
        command: cd AndroidDemo; ./gradlew cAT
    - store_artifacts:
        path: AndroidDemo/app/build/reports/androidTests/connected
    - store_test_results:
        path: AndroidDemo/app/build/reports/androidTests/connected
    

