version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
    - image: circleci/android:api-27-alpha
    environment:
    - CIRCLE_COMPARE_URL: https://github.com/vietthanhle89/EspressoCircleCI/compare/5184e7b5c067...4a4405189a2b
    - JVM_OPTS: -Xmx3200m
    steps:
    - checkout
    - run:
        name: Copy SDK License
        command: (echo y; echo y; echo y; echo y; echo y; echo y) | $ANDROID_HOME/tools/bin/sdkmanager --licenses
    - run:
        name: Create emulator
        command: "set -e\nsdkmanager \"system-images;android-22;default;armeabi-v7a\"\necho \"no\" | avdmanager create avd -n ThanhLeDevice -k \"system-images;android-22;default;armeabi-v7a\"\navdmanager list           \n"
    - run:
        name: Launch emulator
        command: emulator -avd ThanhLeDevice -noaudio -no-boot-anim -no-window -accel on
        background: true
    - run:
        name: Wait emulator
        command: circle-android wait-for-boot
    - run:
        name: Check devices
        command: |
          adb devices
          adb shell settings put global development_settings_enabled 1
          adb shell settings put global window_animation_scale 0 &
          adb shell settings put global transition_animation_scale 0 &
          adb shell settings put global animator_duration_scale 0 &
    - run:
        name: Download Dependencies
        command: cd AndroidDemo; ./gradlew androidDependencies
    - run:
        name: Run EspressoTests
        command: cd AndroidDemo; ./gradlew cAT
   - run:
        name: Create Test Result directory
        command: mkdir /tmp/test-results
    - store_test_results:
        path: /tmp/test-results

    - store_artifacts:
        path: /tmp/test-results
        destination: test_results
